# Generated by Django 2.2.2 on 2019-12-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ph',
            new_name='gasdb',
        ),
        migrations.RenameModel(
            old_name='sound',
            new_name='phdb',
        ),
        migrations.RenameModel(
            old_name='gas',
            new_name='sounddb',
        ),
    ]
